// Super-admin-only leg, kept separate from user_flow_test.dart rather
// than folded in — createOrganization (functions/src/admin.ts) requires
// role: ['super-admin'], a genuinely different account/session than the
// plain admin one that test uses throughout, so it can't share that
// session. Runs via `patrol test --device chrome` against real Chrome,
// real Firebase Auth/Firestore/Cloud Functions on amdash-dev, same as
// every other patrol_test suite in this repo. The throwaway super-admin
// account is created directly via the Firebase Admin SDK, not by this
// test — pass its email/password via --dart-define, same convention as
// every other test in this suite.
//
// Doesn't verify organization.create's own audit log entry here — unlike
// every other action in this suite, a pure super-admin structurally can't:
// listAuditLog's own requireAdmin call needs the plain 'admin' role plus a
// real organizationId (functions/src/admin.ts), neither of which a
// super-admin has (they're not a member of any org, by design — see
// createOrganization's own comment). The entry the newly-created org's own
// first admin *could* see requires that brand-new, still-passwordless
// account to complete a full first-login flow just to check one row — see
// run-admin-patrol-test.mjs's own verifyOrganizationCreateAuditEntry
// instead, which reads the entry directly via the Admin SDK after this
// test completes, bypassing the UI limitation entirely rather than
// building a second onboarding flow just for this one check.
//
// tapKey/tapText/enterTextAt/pumpUntil/completeMfaEnrollment come from
// amdash_patrol_helpers, shared across every app's patrol_test/ suite —
// see that package for the full rationale/history behind each one.
import 'package:admin/main.dart';
import 'package:admin/screens/organization_management_screen.dart';
import 'package:amdash_patrol_helpers/amdash_patrol_helpers.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

import 'package:admin/firebase_options.dart';

void main() {
  patrolTest(
    'super-admin creates an organization and its first admin',
    ($) async {
      const email = String.fromEnvironment('SMOKE_EMAIL');
      const password = String.fromEnvironment('SMOKE_PASSWORD');
      // Generated by run-admin-patrol-test.mjs, not here — unlike this
      // suite's other throwaway names (which nothing outside the test
      // itself needs to know), the script has to query for this exact
      // organization.create audit entry afterward via the Admin SDK (see
      // this file's own header comment for why it can't be checked
      // through the UI), so it needs the same name this test used.
      const organizationName = String.fromEnvironment('SMOKE_ORG_NAME');
      expect(email, isNotEmpty, reason: 'pass --dart-define=SMOKE_EMAIL=...');
      expect(
        password,
        isNotEmpty,
        reason: 'pass --dart-define=SMOKE_PASSWORD=...',
      );
      expect(
        organizationName,
        isNotEmpty,
        reason: 'pass --dart-define=SMOKE_ORG_NAME=...',
      );

      final newAdminEmail =
          'patrol-org-admin-${DateTime.now().millisecondsSinceEpoch}@amdash-e2e.test';

      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      await $.pumpWidgetAndSettle(const ProviderScope(child: AdminApp()));

      // Sign in.
      await $(TextField).at(0).enterText(email);
      await tapText($, 'Continue');
      await pumpUntil($, () => find.text('Sign In').evaluate().isNotEmpty);

      await $(TextField).at(0).enterText(password);
      await tapText($, 'Sign In');

      await completeMfaEnrollment($);

      // Landing redirect sends a super-admin (with no admin role of their
      // own) to /organizations — a plain admin lands on /users instead.
      await pumpUntil(
        $,
        () => find.byType(OrganizationManagementScreen).evaluate().isNotEmpty,
        maxIterations: 50,
      );
      expect(
        find.byType(OrganizationManagementScreen),
        findsOneWidget,
        reason: 'should have reached the organizations screen',
      );

      // Create the organization + its first admin, atomically — there's
      // deliberately no "create an empty organization" path (see this
      // screen's own doc comment).
      await enterTextAt($, 0, organizationName);
      await enterTextAt($, 1, newAdminEmail);
      await enterTextAt($, 2, 'Patrol');
      await enterTextAt($, 3, 'OrgAdmin');
      await tapKey($, 'organization_country_dropdown');
      await pumpUntil(
        $,
        () => find.byKey(const Key('organization_country_option_CA')).evaluate().isNotEmpty,
      );
      await tapKey($, 'organization_country_option_CA');
      // Scoped to the organizations Table, not a bare find.text(organizationName)
      // — the form's own Organization Name field doesn't clear until
      // _createOrganization() actually succeeds, so for a moment both the
      // still-filled TextField and the new table row show the same text.
      // Same class of bug, same fix, as user_flow_test.dart's own hospital-
      // creation assertion.
      final orgRow = find.descendant(
        of: find.byType(Table),
        matching: find.text(organizationName),
      );
      // Retries the whole submit tap, not just the wait — a dropped tap and
      // a slow round trip look identical from here (confirmed for real:
      // this exact step missed a single 16s wait on a loaded dev machine).
      // Safe to retry the tap itself here specifically (unlike most
      // create actions in this suite, which only get one attempt):
      // createOrganization rejects a duplicate organizationName server-side
      // (functions/src/admin.ts), so a retry against an already-succeeded
      // first attempt just surfaces a harmless "already-exists" error on
      // the form — the row from the real first success is already there
      // either way, same reasoning as toggleSwitchAndWait's own retry
      // (amdash_patrol_helpers).
      for (var attempt = 0; attempt < 3; attempt++) {
        await tapKey($, 'create_organization_submit');
        await pumpUntil($, () => orgRow.evaluate().isNotEmpty, maxIterations: 40);
        if (orgRow.evaluate().isNotEmpty) break;
      }
      expect(
        orgRow,
        findsOneWidget,
        reason: 'organization should have been created within the retry budget',
      );
      // organization.create's own audit entry is verified by
      // run-admin-patrol-test.mjs directly via the Admin SDK after this
      // test completes — see this file's own header comment for why not
      // here.
    },
  );
}
