// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOpM_Mi9NcMeZS8sD42olEMyN_MjVl5k',
    appId: '1:577422583971:web:488d6ba962843f924fb716',
    messagingSenderId: '577422583971',
    projectId: 'amdash-dev',
    authDomain: 'amdash-dev.firebaseapp.com',
    storageBucket: 'amdash-dev.firebasestorage.app',
    measurementId: 'G-QXETV3X3MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYah_IMtotFPXcFbSVMfwPs9n_YpOGOQ',
    appId: '1:577422583971:android:08f6795a6a9af1a84fb716',
    messagingSenderId: '577422583971',
    projectId: 'amdash-dev',
    storageBucket: 'amdash-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVw6VdBrfJ36MRP4-7qBhLDOPJ-fYg-s0',
    appId: '1:577422583971:ios:427a94985db8fabb4fb716',
    messagingSenderId: '577422583971',
    projectId: 'amdash-dev',
    storageBucket: 'amdash-dev.firebasestorage.app',
    iosBundleId: 'com.amdash.ems',
  );
}
